nelmio_api_doc:
    documentation:
        info:
            title: Api Doc
            description: This is Bilemo Api Doc!
            version: 1.0.0
        host: http://127.0.0.1:8000/api/doc
        schemes: [http, https]
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
